version: '3.9'

services:
  rabbit:
    image: rabbitmq:3.12.3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: flitter
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci